In [217]:

import numpy as np
import pandas as pd
from zmq.backend import first

#导包

In [218]:
movie_df = pd.read_csv('movie.csv', encoding='utf-8')
movie_df.head()
#导入数据

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [219]:
#检查缺失值
print(movie_df.isnull())
movie_df.info

      Rank  Title  Genre  Description  Director  Actors   Year  \
0    False  False  False        False     False   False  False
1    False  False  False        False     False   False  False
2    False  False  False        False     False   False  False
3    False  False  False        False     False   False  False
4    False  False  False        False     False   False  False
..     ...    ...    ...          ...       ...     ...    ...
995  False  False  False        False     False   False  False
996  False  False  False        False     False   False  False
997  False  False  False        False     False   False  False
998  False  False  False        False     False   False  False
999  False  False  False        False     False   False  False

     Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore
0                False   False  False               False      False
1                False   False  False               False      False
2                False   False  False               False      False
3                False   False  False               False      False
4                False   False  False               False      False
..                 ...     ...    ...                 ...        ...
995              False   False  False                True      False
996              False   False  False               False      False
997              False   False  False               False      False
998              False   False  False                True      False
999              False   False  False               False      False

[1000 rows x 12 columns]

<bound method DataFrame.info of      Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2               Prometheus  Adventure,Mystery,Sci-Fi
2       3                    Split           Horror,Thriller
3       4                     Sing   Animation,Comedy,Family
4       5            Suicide Squad  Action,Adventure,Fantasy
..    ...                      ...                       ...
995   996     Secret in Their Eyes       Crime,Drama,Mystery
996   997          Hostel: Part II                    Horror
997   998   Step Up 2: The Streets       Drama,Music,Romance
998   999             Search Party          Adventure,Comedy
999  1000               Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
995  A tight-knit team of rising investigators, alo...             Billy Ray
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
998  A pair of friends embark on a mission to reuni...        Scot Armstrong
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
..                 ...     ...     ...                 ...        ...
995                111     6.2   27585                 NaN       45.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
998                 93     5.6    4881                 NaN       22.0
999                 87     5.3   12435               19.64       11.0

[1000 rows x 12 columns]>

In [220]:
#处理缺失值
for column in movie_df.columns:
    if np.all(pd.notnull(movie_df[column])) == False:
        movie_df.dropna(axis=0, inplace=True)
movie_df.info

<bound method DataFrame.info of      Rank                     Title                     Genre  \
0       1   Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2                Prometheus  Adventure,Mystery,Sci-Fi
2       3                     Split           Horror,Thriller
3       4                      Sing   Animation,Comedy,Family
4       5             Suicide Squad  Action,Adventure,Fantasy
..    ...                       ...                       ...
993   994  Resident Evil: Afterlife   Action,Adventure,Horror
994   995                 Project X                    Comedy
996   997           Hostel: Part II                    Horror
997   998    Step Up 2: The Streets       Drama,Music,Romance
999  1000                Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
993  While still out to destroy the evil Umbrella C...    Paul W.S. Anderson
994  3 high school seniors throw a birthday party t...       Nima Nourizadeh
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
993  Milla Jovovich, Ali Larter, Wentworth Miller,K...  2010
994  Thomas Mann, Oliver Cooper, Jonathan Daniel Br...  2012
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
..                 ...     ...     ...                 ...        ...
993                 97     5.9  140900               60.13       37.0
994                 88     6.7  164088               54.72       48.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
999                 87     5.3   12435               19.64       11.0

[838 rows x 12 columns]>

In [221]:
rate_counts = movie_df['Rating'].value_counts().sort_index()
rate_counts
#评分分布

Rating
1.9     1
2.7     1
3.9     2
4.0     1
4.1     1
4.3     3
4.4     1
4.6     2
4.7     3
4.8     1
4.9     6
5.0     1
5.1     5
5.2     6
5.3     8
5.4    10
5.5    11
5.6    13
5.7    16
5.8    21
5.9    15
6.0    20
6.1    22
6.2    33
6.3    36
6.4    30
6.5    35
6.6    37
6.7    42
6.8    33
6.9    23
7.0    43
7.1    40
7.2    38
7.3    37
7.4    29
7.5    33
7.6    26
7.7    25
7.8    38
7.9    20
8.0    19
8.1    24
8.2     9
8.3     5
8.4     2
8.5     6
8.6     3
8.8     1
9.0     1
Name: count, dtype: int64

In [222]:
#评分最高的20部
movie_best = movie_df.sort_values('Rating', ascending=False)
movie_best[:20]['Title']

54            The Dark Knight
80                  Inception
36               Interstellar
249          The Intouchables
96              Kimi no na wa
124     The Dark Knight Rises
991          Taare Zameen Par
133                  Whiplash
99               The Departed
476       The Lives of Others
64               The Prestige
144          Django Unchained
430                  3 Idiots
455                    Jagten
499                        Up
688               Toy Story 3
77       Inglourious Basterds
6                  La La Land
765                        PK
742    El secreto de sus ojos
Name: Title, dtype: object

In [223]:
#先提取所有类型
genre_series = movie_df.Genre
dict = {}
for genre in genre_series:
    genre_list = genre.strip().split(',')
    for i in genre_list:
        if i not in dict.keys():
            dict[i] = 0
dict_sort = sorted(dict.items(), key=lambda x: x[0], reverse=False)

dict1 = {}

for t in dict_sort:
    dict1[t[0]] = t[1]
print(dict1)
print(len(dict1))
dict2 = dict1

{'Action': 0, 'Adventure': 0, 'Animation': 0, 'Biography': 0, 'Comedy': 0, 'Crime': 0, 'Drama': 0, 'Family': 0, 'Fantasy': 0, 'History': 0, 'Horror': 0, 'Music': 0, 'Musical': 0, 'Mystery': 0, 'Romance': 0, 'Sci-Fi': 0, 'Sport': 0, 'Thriller': 0, 'War': 0, 'Western': 0}
20

In [224]:
#再进行计数
for genre in genre_series:
    genre_list = genre.strip().split(',')
    for ele in genre_list:
        if ele in dict2.keys():
            dict2[ele] += 1

data_df = pd.DataFrame(
    list(dict2.items()),  # 使用items()确保顺序一致
    columns=['genre', 'count']
)

# 按count降序排序，并重置索引
data_df = data_df.sort_values(by='count', ascending=False).reset_index(drop=True)

print("电影类型统计:")
print(data_df)

电影类型统计:
        genre  count
0       Drama    419
1      Action    277
2      Comedy    250
3   Adventure    244
4    Thriller    148
5       Crime    126
6     Romance    120
7      Sci-Fi    107
8     Fantasy     92
9      Horror     87
10    Mystery     86
11  Biography     67
12     Family     48
13  Animation     45
14    History     25
15      Music     15
16      Sport     15
17        War     10
18    Musical      5
19    Western      4

In [225]:
#各类型的平均评分与排名
data1 = movie_df.groupby(['Genre']).agg({'Rating': 'mean', 'Rank': 'mean'})
data1 = data1[['Rating', 'Rank']].round(1)
data1.sort_values(by=['Rating', 'Rank'], ascending=[False, False], inplace=True)
data1

                         Rating   Rank
Genre
Animation,Drama,Fantasy     8.6   97.0
Drama,Family,Music          8.5  992.0
Drama,Western               8.4  145.0
Adventure,Drama,War         8.3   78.0
Adventure,Drama,Sci-Fi      8.3   70.0
...                         ...    ...
Action,Fantasy,Thriller     5.2  586.0
Drama,Horror,Thriller       5.1  212.3
Sci-Fi,Thriller             5.0  513.0
Action                      4.9  581.0
Sci-Fi                      4.0  617.0

[189 rows x 2 columns]

In [241]:
# 类型流行趋势
data2 = movie_df[['Year', 'Genre']]
data2.groupby(['Year']).agg({'Genre': 'count'})  #每年的类型数量
data2['Genre_list'] = data2['Genre'].str.split(',')
# print(data2)
data2 = data2.explode('Genre_list')  #explode方法是将一个单元格中的列表，每个元素都拿出来，形成一列
# print(data2)
series1 = data2.groupby(['Year', 'Genre_list']).size().reset_index(name='count')  #- 功能 ：计算每个分组中的元素数量
#- 输出 ：返回一个Series，索引是分组键(年份和类型)，值是该分组的大小

data_series1 = pd.DataFrame(series1)
data_series1

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\2367535104.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Genre_list']=data2['Genre'].str.split(',')

     Year Genre_list  count
0    2006     Action     10
1    2006  Adventure     12
2    2006  Animation      2
3    2006  Biography      3
4    2006     Comedy     12
..    ...        ...    ...
187  2016     Sci-Fi     14
188  2016      Sport      3
189  2016   Thriller     29
190  2016        War      2
191  2016    Western      1

[192 rows x 3 columns]

In [242]:
#不同类型的电影的评分分布对比
data3 = movie_df[['Genre', 'Rating']]
data3['Genre_list'] = data3['Genre'].str.split(',')
date3_exploded = data3.explode('Genre_list')
data3_1 = date3_exploded.groupby(['Genre_list']).agg({'Rating': 'mean'}).round(2).sort_values(by=['Rating'],
                                                                                              ascending=[False])
data3_1

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\2672069187.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3['Genre_list']=data3['Genre'].str.split(',')

            Rating
Genre_list
War           7.60
Biography     7.35
History       7.32
Animation     7.31
Western       7.25
Music         7.17
Sport         7.09
Drama         7.04
Mystery       6.97
Musical       6.94
Crime         6.90
Adventure     6.80
Thriller      6.79
Sci-Fi        6.77
Comedy        6.71
Romance       6.70
Family        6.67
Action        6.65
Fantasy       6.63
Horror        6.29

In [228]:
#电影产量随时间变化（按年份）
data4 = movie_df[['Title', 'Year']]
data4_1 = data4.groupby(['Year']).agg(Count=('Title', 'count'))
data4_1

      Count
Year
2006     41
2007     44
2008     48
2009     45
2010     57
2011     57
2012     62
2013     84
2014     93
2015    109
2016    198

In [243]:
#电影产量随时间变化（按年代）
data4['Decade'] = (data4['Year'] // 10 * 10).astype(str)  #添加一列年代
decade_counts = data4.groupby(['Decade']).agg({'Title': 'count'}).reset_index()
decade_counts

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\466953875.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data4['Decade']=(data4['Year'] //10*10).astype(str)   #添加一列年代

  Decade  Title
0   2000    178
1   2010    660

In [244]:
#不同年代的电影的平均评分对比
data5 = movie_df[['Rating', 'Year']]
data5_1 = data5.groupby('Year').agg({'Rating': 'mean'}).round(2).sort_values(by='Rating', ascending=False)
# print(data5_1)

data5['Decade'] = (data5['Year'] // 10 * 10).astype(str)  #添加一列年代
data5_2 = data5.groupby(['Decade']).agg({'Rating': 'mean'})
data5_2

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\3809959789.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data5['Decade']=(data5['Year'] //10 *10).astype(str) #添加一列年代

          Rating
Decade
2000    6.966854
2010    6.773182

In [231]:
#电影时长随时间的变化趋势
data6 = movie_df[['Year', 'Runtime (Minutes)']]
data6['Decade'] = (data6['Year'] // 10 * 10).astype(str)  #添加一列年代

data6_1 = data6.groupby(['Decade']).agg({'Runtime (Minutes)': 'mean'}).round(2)
data6_1

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\329849892.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data6['Decade']=(data6['Year'] //10 *10).astype(str) #添加一列年代

        Runtime (Minutes)
Decade
2000               117.15
2010               113.96

In [232]:
#最佳的电影时长是多少（评分最高的时长区间）
data7 = movie_df[['Rating', 'Runtime (Minutes)']]
data7['Runtime (Minutes)'] = data7['Runtime (Minutes)'] / 60
data7.rename({'Runtime (Minutes)': 'Runtime (Hours)'}, axis=1, inplace=True)
data7['Runtime (Hours)'].max()
bins = [0, 1.5, 2, 2.5, 3]  #每两个值之间为一个区间

data7['Runtime_Interval'] = pd.cut(
    data7['Runtime (Hours)'],  #需要分类的数据
    bins=bins,
    labels=['短', '中', '长', '超长'],  #每一列的标签

)

runtime_counts = data7["Runtime_Interval"].value_counts().sort_index()
runtime_counts_df = pd.DataFrame(data=runtime_counts).reset_index(drop=False)
runtime_counts_df

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\2947029251.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data7['Runtime (Minutes)']=data7['Runtime (Minutes)']/60
C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\2947029251.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data7.rename({'Runtime (Minutes)':'Runtime (Hours)'}, axis=1, inplace=True)
C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\2947029251.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data7['Runtime_Interval']=pd.cut(

  Runtime_Interval  count
0                短     48
1                中    529
2                长    218
3               超长     42

In [233]:
#不同类型电影的时长的差异
data8 = movie_df[['Genre', 'Runtime (Minutes)']].copy()
data8['Genre_list'] = data8['Genre'].str.split(',')
data8_exploded = data8.explode('Genre_list')
data8_1 = data8_exploded.groupby(['Genre_list']).agg({'Runtime (Minutes)': 'mean'}).round(2).sort_values(
    by=['Runtime (Minutes)'], ascending=[False])
data8_1

            Runtime (Minutes)
Genre_list
History                131.80
Western                130.75
Musical                127.60
Biography              123.13
Sport                  120.13
Fantasy                118.46
Drama                  118.36
Adventure              118.11
Sci-Fi                 117.69
Crime                  117.67
Action                 117.02
War                    116.70
Mystery                116.19
Thriller               114.18
Romance                113.08
Music                  112.00
Family                 111.79
Comedy                 106.56
Horror                 102.93
Animation               97.69

In [234]:
#高产导演top20

data9 = movie_df[['Director', 'Title']].copy()
data9_1 = data9.groupby(['Director']).agg({'Title': 'count'}).reset_index().sort_values(by=['Title'], ascending=[False])
data9_1.head(20)

               Director  Title
417        Ridley Scott      8
126         David Yates      6
341         Michael Bay      6
391  Paul W.S. Anderson      6
200         J.J. Abrams      5
106         Danny Boyle      5
128    Denis Villeneuve      5
36        Antoine Fuqua      5
518         Woody Allen      5
332     Martin Scorsese      5
284          Justin Lin      5
88    Christopher Nolan      5
522         Zack Snyder      5
114       David Fincher      5
317  M. Night Shyamalan      5
396          Peter Berg      5
398       Peter Jackson      4
187         Guy Ritchie      4
311     Louis Leterrier      4
185  Guillermo del Toro      4

In [235]:
#高评分导演Top20
data10 = movie_df[['Director', 'Title', 'Rating']].copy()
data10_1 = data10.groupby(['Director']).agg({'Rating': 'mean', 'Title': 'count'}).reset_index().sort_values(
    by=['Rating'], ascending=[False])
data10_1[data10_1['Title'] >= 4][:20]['Director']

88      Christopher Nolan
332       Martin Scorsese
114         David Fincher
128      Denis Villeneuve
336        Matthew Vaughn
200           J.J. Abrams
398         Peter Jackson
126           David Yates
187           Guy Ritchie
255           Jon Favreau
106           Danny Boyle
119      David O. Russell
48            Ben Affleck
213             James Wan
185    Guillermo del Toro
36          Antoine Fuqua
522           Zack Snyder
155      Francis Lawrence
518           Woody Allen
2              Adam McKay
Name: Director, dtype: object

In [236]:
#导演的票房表现
data11 = movie_df[['Director', 'Revenue (Millions)']].copy()
#缺失值处理
data11.dropna(inplace=True)
#分析
data11_1 = data11.groupby(['Director']).agg({'Revenue (Millions)': 'sum'}).reset_index().sort_values(
    by=['Revenue (Millions)'], ascending=[False])
data11_1

              Director  Revenue (Millions)
200        J.J. Abrams             1683.45
126        David Yates             1630.51
88   Christopher Nolan             1515.09
341        Michael Bay             1421.32
155   Francis Lawrence             1299.81
..                 ...                 ...
186       Gus Van Sant                0.02
427      Robin Swicord                0.01
464        So Yong Kim                0.01
384    Patricia Rozema                0.01
27        Andy Goddard                0.00

[524 rows x 2 columns]

In [237]:
#导演类型偏好分析
data12 = movie_df[['Director', 'Genre']].copy()
data12['Genre_list'] = data12['Genre'].str.split(',')
data12_exploded = data12.explode('Genre_list')
data12_1 = data12_exploded.groupby(['Director', 'Genre_list']).size().reset_index(name='count')

# 找出每个导演计数最高的类型
top_genres_by_director = data12_1.groupby('Director').apply(
    lambda x: x.nlargest(1, 'count')  # nlargest:前n大 的值, x指的是每个分类的dataframe
).reset_index(drop=True)

# 按计数排序
top_genres_by_director = top_genres_by_director.sort_values('count', ascending=False)

print("每个导演最擅长的类型 (按计数排序):")
top_genres_by_director.head(20)

每个导演最擅长的类型 (按计数排序):

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\3110857562.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_genres_by_director = data12_1.groupby('Director').apply(

               Director Genre_list  count
417        Ridley Scott      Drama      7
126         David Yates  Adventure      6
391  Paul W.S. Anderson     Action      6
284          Justin Lin     Action      5
114       David Fincher      Drama      5
522         Zack Snyder     Action      5
341         Michael Bay     Action      5
106         Danny Boyle      Drama      4
129        Dennis Dugan     Comedy      4
48          Ben Affleck      Drama      4
36        Antoine Fuqua     Action      4
187         Guy Ritchie     Action      4
398       Peter Jackson    Fantasy      4
396          Peter Berg     Action      4
301      Lars von Trier      Drama      4
368    Nicholas Stoller     Comedy      4
200         J.J. Abrams     Action      4
518         Woody Allen    Romance      4
2            Adam McKay     Comedy      4
213           James Wan   Thriller      4

In [238]:
#出演电影最多的演员top20
data13 = movie_df[['Actors', 'Title']].copy()
data13['Actor_list'] = data13['Actors'].str.split(',')
data13_exploded = data13.explode('Actor_list')

data13_1 = data13_exploded.groupby(['Actor_list']).agg({'Title': 'count'}).sort_values(by=['Title'], ascending=[False])
data13_1.head(20)

                     Title
Actor_list
Christian Bale          11
Mark Wahlberg           11
Jake Gyllenhaal          9
 Rose Byrne              9
Brad Pitt                9
 Woody Harrelson         9
Leonardo DiCaprio        9
Tom Hanks                8
 Anne Hathaway           8
Will Smith               8
 Joel Edgerton           8
Denzel Washington        8
 Michelle Monaghan       8
 Morgan Freeman          8
Adam Sandler             8
 Scarlett Johansson      8
Matthew McConaughey      8
 Cate Blanchett          8
 Hugh Jackman            8
Robert Downey Jr.        8

In [239]:
#电影评分最高的演员（主演）
data14 = movie_df[['Actors', 'Rating']].copy()
main_actor = []
for i in range(data14.shape[0]):
    name_list = data14['Actors'].iloc[i].split(',')  #手搓
    main_actor.append(name_list[0])
name_series = pd.Series(main_actor)
name_series.dropna(inplace=True)
data14['Actor_main'] = name_series
data14_1 = data14.groupby(['Actor_main']).agg({'Rating': 'mean'}).reset_index().sort_values(by=['Rating'],
                                                                                            ascending=[False])
data14_1.nlargest(1, 'Rating', keep='all')

        Actor_main  Rating
357  Travis Fimmel     8.8

In [240]:
#演员类型偏好
data15 = movie_df[['Actors', 'Genre']].copy()
main_actor = []
for i in range(0, data15.shape[0]):
    name_list = data15['Actors'].iloc[i].split(',')  #手搓
    main_actor.append(name_list[0])
name_series = pd.Series(main_actor)
name_series.dropna()
data15['Actor_main'] = name_series
data15['Genre_list'] = data15['Genre'].str.split(',')
data15_exploded = data15.explode('Genre_list')
data15_1 = data15_exploded.groupby(['Actor_main', 'Genre_list']).size().reset_index(name='count')

top_genres_by_actor = data15_1.groupby(['Actor_main']).apply(lambda x: x.nlargest(1, 'count')).reset_index(drop=True)
top_genres_by_actor

C:\Users\icyw\AppData\Local\Temp\ipykernel_29172\2203288632.py:14: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_genres_by_actor=data15_1.groupby(['Actor_main']).apply(lambda x:x.nlargest(1, 'count')).reset_index(drop=True)

               Actor_main Genre_list  count
0              Aamir Khan     Comedy      1
1              Aaron Paul    Mystery      1
2             Aaron Poole      Crime      1
3    Aaron Taylor-Johnson     Family      2
4            Adam Sandler     Action      3
..                    ...        ...    ...
369             Zac Efron      Drama      3
370     Zach Galifianakis     Action      2
371        Zachary Gordon     Action      2
372           Zoey Deutch  Adventure      1
373       Zooey Deschanel      Drama      1

[374 rows x 3 columns]